<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findProductsForShow($visible = true)
    {
        return $this->createQueryBuilder('p')
            ->where('p.visiblity = :visible')
            ->setParameter('visible', $visible)
            ->getQuery()
            ->getResult();
    }

    public function getProductsByCats($cats)
    {
        return $this->createQueryBuilder('p')
            ->innerJoin('p.category', 'c', 'with', 'c.id IN :cats')
            ->setParameter('cats' , $cats)
            ->getQuery()
            ->getResult();
    }
}
